### ISSUE TITLE
ValueError: shapes not aligned 

### ISSUE THREAD

**Issue by marcasriv** [lareaulab/iXnos#1]
Hi,

I am currently trying to run the section 'Optimizing Gene Sequences Under a Neural Network Model' with only codon features and default parameters . However, I keep getting an error that seems to be originated in a numpy dependency:
I am running:

`
min_seq, min_score = inter.get_lasagne_optimal_codons(
... nn_dir, epoch, aa_seq, maximum=False, nt_feats=nt_feats)
`

with

` epoch = 30 
`
`
aa_seq = "MACDEFGHIKLNPQRSTVWY"
`

Making dense mlp
nonnegative model
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/interface.py", line 757, in get_lasagne_optimal_codons
    aa_seq, my_nn, rel_cod_idxs, maximum=maximum, nt_feats=nt_feats)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/optimizecodons.py", line 365, in get_optimal_codons_lasagne
    aa_seq, nn, rel_cod_idxs, nt_feats=nt_feats)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/optimizecodons.py", line 307, in get_seqs_to_lasagne_outputs_by_pos
    aa_seq, i, nn, rel_cod_idxs, nt_feats=nt_feats)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/optimizecodons.py", line 192, in get_seqs_to_lasagne_outputs
    pred_outputs = my_nn.pred_fn(feat_matrix)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 892, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/basic.py", line 5951, in perform
    z[0] = np.asarray(np.dot(x, y))
ValueError: shapes (192,640) and (760,200) not aligned: 640 (dim 1) != 760 (dim 0)
Apply node that caused the error: dot(inputs, W)
Toposort index: 2
Inputs types: [TensorType(int64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(192, 640), (760, 200)]
Inputs strides: [(8, 1536), (1600, 8)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{tanh((i0 + i1))}}[(0, 0)](dot.0, InplaceDimShuffle{x,0}.0)]]
`
`
Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "<stdin>", line 2, in <module>
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/interface.py", line 749, in get_lasagne_optimal_codons
    my_nn = load_lasagne_feedforward_nn(nn_dir, epoch)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/interface.py", line 481, in load_lasagne_feedforward_nn
    reloaded=True)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/lasagnenn.py", line 402, in __init__
    self.te_pred_var = self.get_te_pred_var(self.network)
  File "/home/marina/git-repos/iXnos/iXnos/iXnos/lasagnenn.py", line 147, in get_te_pred_var
    return lasagne.layers.get_output(network, deterministic=True)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 197, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/dense.py", line 121, in get_output_for
    activation = T.dot(input, self.W)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
`

From what I understand from "ValueError: shapes (192,640) and (760,200) not aligned: 640 (dim 1) != 760 (dim 0)", the shapes in the model are imported as arrays, so the number of columns of the first matrix has to be the same a the number of rows in the second matrix ; otherwise, it throws an error. However, I don't quite understand how the shapes are generated and therefore the origin of the error. I'd enormously appreciate any help.

Thank you very much!

Kind regards,

Marina

**Comment by lcscs12345** [comment]
Hi Marina,

I encountered the same errors. It will work when you stick to the same rel_cod_idxs/rel_nt_idxs for training NN and loading the model for gene optimization. 

Cheers
Lim

**Comment by marcasriv** [comment]
Hi Lim,

Thanks a lot for your reply. I did as you said and it worked!

Thanks again.

Best,

Marina
